import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  UserCog, Star, TrendingUp, Clock, Award, BarChart3,
  Scissors, Sparkles, Zap
} from 'lucide-react';
import GlassCard from '../components/ui/GlassCard';
import Badge from '../components/ui/Badge';
import KpiCard from '../components/ui/KpiCard';

// Demo data — Backend doesn't have Employee model yet
const DEMO_EMPLOYEES = [
  { id: 1, name: 'Priya Sharma', role: 'Senior Stylist', avatar: 'PS', rating: 4.9, bookings: 342, revenue: 285000, utilization: 92, skills: ['Hair Color', 'Keratin', 'Blowout', 'Haircut'], experience: '6 years', status: 'active' },
  { id: 2, name: 'Anjali Deshmukh', role: 'Beauty Expert', avatar: 'AD', rating: 4.8, bookings: 298, revenue: 245000, utilization: 87, skills: ['Facial', 'Cleanup', 'Threading', 'Waxing'], experience: '4 years', status: 'active' },
  { id: 3, name: 'Meena Patil', role: 'Nail Technician', avatar: 'MP', rating: 4.7, bookings: 256, revenue: 198000, utilization: 78, skills: ['Manicure', 'Pedicure', 'Detan'], experience: '3 years', status: 'active' },
  { id: 4, name: 'Rashmi Kulkarni', role: 'Hair Specialist', avatar: 'RK', rating: 4.6, bookings: 234, revenue: 187000, utilization: 82, skills: ['Haircut', 'Hair Color', 'Keratin', 'Blowout'], experience: '5 years', status: 'active' },
  { id: 5, name: 'Sneha Joshi', role: 'Massage Therapist', avatar: 'SJ', rating: 4.9, bookings: 189, revenue: 312000, utilization: 71, skills: ['Massage', 'Detan', 'Facial'], experience: '7 years', status: 'active' },
  { id: 6, name: 'Kavita Agrawal', role: 'Junior Stylist', avatar: 'KA', rating: 4.3, bookings: 156, revenue: 124000, utilization: 64, skills: ['Threading', 'Waxing', 'Cleanup'], experience: '1 year', status: 'active' },
];

const gradientAvatars = [
  'from-aurora-purple to-aurora-indigo',
  'from-aurora-cyan to-aurora-teal',
  'from-aurora-pink to-aurora-rose',
  'from-aurora-gold to-aurora-amber',
  'from-emerald-400 to-teal-500',
  'from-violet-500 to-purple-600',
];

export default function EmployeesPage() {
  const [selectedEmployee, setSelectedEmployee] = useState(null);

  const totalBookings = DEMO_EMPLOYEES.reduce((s, e) => s + e.bookings, 0);
  const totalRevenue = DEMO_EMPLOYEES.reduce((s, e) => s + e.revenue, 0);
  const avgRating = (DEMO_EMPLOYEES.reduce((s, e) => s + e.rating, 0) / DEMO_EMPLOYEES.length).toFixed(1);
  const avgUtilization = Math.round(DEMO_EMPLOYEES.reduce((s, e) => s + e.utilization, 0) / DEMO_EMPLOYEES.length);

  return (
    <div className="space-y-6 max-w-[1400px] mx-auto">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-display font-bold text-ink-900 tracking-tight">Employee Management</h1>
          <p className="text-sm text-ink-400 mt-1">Performance tracking and skills overview.</p>
        </div>
        <Badge variant="warning">
          <Sparkles className="w-3 h-3" /> Demo Mode
        </Badge>
      </motion.div>

      {/* KPI Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <KpiCard icon={UserCog} label="Total Staff" numericValue={DEMO_EMPLOYEES.length} sub="Active employees" accent="purple" delay={0} />
        <KpiCard icon={TrendingUp} label="Total Revenue" numericValue={totalRevenue} prefix="₹" sub="Generated by staff" accent="cyan" delay={0.05} />
        <KpiCard icon={Star} label="Avg Rating" value={avgRating} sub="Customer satisfaction" accent="gold" delay={0.1} />
        <KpiCard icon={BarChart3} label="Utilization" value={`${avgUtilization}%`} sub="Average workload" accent="emerald" delay={0.15} />
      </div>

      {/* Employee Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {DEMO_EMPLOYEES.map((emp, i) => (
          <motion.div
            key={emp.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.06, duration: 0.4 }}
            whileHover={{ y: -4 }}
            onClick={() => setSelectedEmployee(selectedEmployee?.id === emp.id ? null : emp)}
            className={`glass-card p-5 cursor-pointer transition-all duration-300 ${
              selectedEmployee?.id === emp.id ? 'glow-border-purple' : ''
            }`}
          >
            <div className="flex items-start gap-4 mb-4">
              {/* Avatar */}
              <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${gradientAvatars[i % gradientAvatars.length]} flex items-center justify-center text-white text-sm font-bold shadow-lg shrink-0`}>
                {emp.avatar}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-base font-bold text-ink-900 truncate">{emp.name}</p>
                <p className="text-xs text-ink-400 font-medium">{emp.role}</p>
                <div className="flex items-center gap-1 mt-1">
                  <Star className="w-3.5 h-3.5 text-aurora-gold fill-aurora-gold" />
                  <span className="text-xs font-bold text-ink-700">{emp.rating}</span>
                  <span className="text-[10px] text-ink-400 ml-1">· {emp.experience}</span>
                </div>
              </div>
              <Badge variant="success">Active</Badge>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-3 gap-3 mb-4">
              <div className="text-center p-2 rounded-lg bg-surface-2/50">
                <p className="text-lg font-bold text-ink-900">{emp.bookings}</p>
                <p className="text-[9px] font-bold uppercase tracking-widest text-ink-400">Bookings</p>
              </div>
              <div className="text-center p-2 rounded-lg bg-surface-2/50">
                <p className="text-lg font-bold text-ink-900">₹{(emp.revenue / 1000).toFixed(0)}K</p>
                <p className="text-[9px] font-bold uppercase tracking-widest text-ink-400">Revenue</p>
              </div>
              <div className="text-center p-2 rounded-lg bg-surface-2/50">
                <p className="text-lg font-bold text-ink-900">{emp.utilization}%</p>
                <p className="text-[9px] font-bold uppercase tracking-widest text-ink-400">Utilization</p>
              </div>
            </div>

            {/* Utilization Bar */}
            <div className="mb-3">
              <div className="w-full h-2 bg-ink-100 rounded-full overflow-hidden">
                <motion.div
                  initial={{ width: 0 }}
                  animate={{ width: `${emp.utilization}%` }}
                  transition={{ duration: 1, delay: 0.3 + i * 0.1 }}
                  className={`h-full rounded-full ${
                    emp.utilization > 85 ? 'bg-aurora-purple' : emp.utilization > 70 ? 'bg-aurora-cyan' : 'bg-aurora-gold'
                  }`}
                />
              </div>
            </div>

            {/* Skills */}
            <div className="flex flex-wrap gap-1.5">
              {emp.skills.map(skill => (
                <span key={skill} className="px-2 py-0.5 rounded-md text-[9px] font-bold uppercase tracking-wider bg-aurora-purple/5 text-aurora-purple border border-aurora-purple/10">
                  {skill}
                </span>
              ))}
            </div>
          </motion.div>
        ))}
      </div>

      {/* Performance Comparison */}
      <GlassCard padding="p-6">
        <h3 className="text-xs font-bold uppercase tracking-widest text-ink-400 mb-5">Performance Leaderboard</h3>
        <div className="space-y-3">
          {[...DEMO_EMPLOYEES].sort((a, b) => b.revenue - a.revenue).map((emp, i) => (
            <div key={emp.id} className="flex items-center gap-4 p-3 rounded-xl hover:bg-surface-2/50 transition-all">
              <span className={`w-8 h-8 rounded-lg flex items-center justify-center text-xs font-bold ${
                i === 0 ? 'bg-aurora-gold/10 text-aurora-gold' : i === 1 ? 'bg-ink-200 text-ink-600' : i === 2 ? 'bg-amber-100 text-amber-700' : 'bg-ink-100 text-ink-400'
              }`}>
                {i === 0 ? '🥇' : i === 1 ? '🥈' : i === 2 ? '🥉' : `#${i + 1}`}
              </span>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-bold text-ink-800">{emp.name}</p>
                <p className="text-[10px] text-ink-400">{emp.role}</p>
              </div>
              <div className="text-right">
                <p className="text-sm font-bold text-ink-800 font-mono">₹{Math.round(emp.revenue).toLocaleString()}</p>
                <p className="text-[10px] text-ink-400">{emp.bookings} bookings</p>
              </div>
              <div className="w-24">
                <div className="w-full h-2 bg-ink-100 rounded-full overflow-hidden">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-aurora-purple to-aurora-cyan"
                    style={{ width: `${(emp.revenue / DEMO_EMPLOYEES[0].revenue * 100)}%` }}
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </GlassCard>
    </div>
  );
}
